export const FETCH_ALL_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_HERO_SLIDER = 'FETCH_HERO_SLIDER'
export const FETCH_IS_LOADING = 'FETCH_IS_LOADING'
export const FETCH_TRENDING_LOADER = 'FETCH_TRENDING_LOADER'
export const FETCH_TRENDING_PRODUCTS = 'FETCH_TRENDING_PRODUCTS'
export const FETCH_BEST_SELLER = 'FETCH_BEST_SELLER'
export const FETCH_BEST_SELLER_LOADING = 'FETCH_BEST_SELLER_LOADING'

export const FETCH_LATES_BLOG = 'FETCH_LATES_BLOG'
export const FETCH_LATES_BLOG_LOADING = 'FETCH_LATES_BLOG_LOADING'
export const FETCH_BLOG = 'FETCH_BLOG'
export const FETCH_BLOG_LOADING = 'FETCH_BLOG_LOADING'
export const FETCH_BLOG_TOTAL = 'FETCH_BLOG_TOTAL'