export const FETCH_ALL_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_ALL_PRODUCTS_LOADING = 'FETCH_ALL_PRODUCTS_LOADING'

export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'
export const FETCH_SINGLE_PRODUCT_LOADING = 'FETCH_SINGLE_PRODUCT_LOADING'

export const FETCH_ALL_PRODUCT_DESC = 'FETCH_ALL_PRODUCT_DESC'
export const FETCH_ALL_PRODUCT_ASC = 'FETCH_ALL_PRODUCT_ASC'


export const FETCH_HERO_SLIDER = 'FETCH_HERO_SLIDER'
export const FETCH_IS_LOADING = 'FETCH_IS_LOADING'
export const FETCH_TRENDING_LOADER = 'FETCH_TRENDING_LOADER'
export const FETCH_TRENDING_PRODUCTS = 'FETCH_TRENDING_PRODUCTS'
export const FETCH_BEST_SELLER = 'FETCH_BEST_SELLER'
export const FETCH_BEST_SELLER_LOADING = 'FETCH_BEST_SELLER_LOADING'

export const FETCH_LATES_BLOG = 'FETCH_LATES_BLOG'
export const FETCH_LATES_BLOG_LOADING = 'FETCH_LATES_BLOG_LOADING'
export const FETCH_BLOG = 'FETCH_BLOG'
export const FETCH_BLOG_LOADING = 'FETCH_BLOG_LOADING'
export const FETCH_BLOG_TOTAL = 'FETCH_BLOG_TOTAL'

export const FETCH_PHOTOS = 'FETCH_PHOTOS'
export const FETCH_PHOTOS_LOADING = 'FETCH_PHOTOS_LOADING'

export const FETCH_DETAIL_POST = 'FETCH_DETAIL_POST'
export const FETCH_DETAIL_POST_LODAING = 'FETCH_DETAIL_POST_LODAING'
export const FETCH_DETAIL_COMMENTS = 'FETCH_DETAIL_COMMENTS'
export const FETCH_DETAIL_COMMENTS_LOADING = 'FETCH_DETAIL_COMMENTS_LOADING'

export const FETCH_POST_AUTH = 'FETCH_POST_AUTH'
export const FETCH_POST_AUTH_LOADING = 'FETCH_POST_AUTH_LOADING'

export const FETCH_CART_BUY = 'FETCH_CART_BUY'
export const FETCH_CART_BUY_LOADING = 'FETCH_CART_BUY_LOADING'
